### ISSUE TITLE
Ability to override the header/footer used for the Pattern Library

### ISSUE THREAD

**Issue by sambulance** [humanmade/kalutara#11]
We will use a default basic header and footer for the display of the pattern library. We may need to override these files with custom headersd and footers.

**Comment by mattheu** [comment]
I have since changed this to remove the `get_header` and `get_footer` calls in the pattern library template, instead only calling `wp_head`. So I don't think this issue is required any more. 

We may need to support adding wrapper divs or similar, which I think is the reason we loaded the header and footer templates. So an alternative approach may need to be explored in future if there are problems with the way it works currently. We can open new issues as the need arises.
